version: 2.1
executors:
  node:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10

jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
workflows:
  version: 2
  test_workflow:
    jobs:
      - test
      - build:
          requires:
            - test
