export const games = [
  {
    game: "The Legend of Zelda",
    year: 1986,
    type: "video",
    players: 1,
    system: "NES",
  },
  {
    game: "Dr. Mario",
    year: 1990,
    type: "video",
    players: 2,
    system: "NES",
  },
  {
    game: "The Legend of Zelda: A Link to the Past",
    year: 1991,
    type: "video",
    players: 1,
    system: "SNES",
  },
  {
    game: "Super Mario World",
    year: 1990,
    type: "video",
    players: 2,
    system: "SNES",
  },
  {
    game: "Donkey Kong Country",
    year: 1994,
    type: "video",
    players: 2,
    system: "SNES",
  },
  {
    game: "Super Mario Kart",
    year: 1992,
    type: "video",
    players: 2,
    system: "SNES",
  },
  {
    game: "Super Mario RPG",
    year: 1996,
    type: "video",
    players: 2,
    system: "SNES",
  },
  {
    game: "Mega Man X",
    year: 1993,
    type: "video",
    players: 2,
    system: "SNES",
  },
  {
    game: "Castle Crashers",
    year: 2019,
    type: "video",
    players: 4,
    system: "Switch",
  },
  {
    game: "Hollow Knight",
    year: 2018,
    type: "video",
    players: 1,
    system: "Switch",
  },
  {
    game: "Mario Kart 8 Deluxe",
    year: 2017,
    type: "video",
    players: 4,
    system: "Switch",
  },
  {
    game: "Super Smash Brothers Ultimate",
    year: 2018,
    type: "video",
    players: 8,
    system: "Switch",
  },
  {
    game: "Resident Evil 7",
    year: 2017,
    type: "video",
    players: 1,
    system: "Playstation 4",
  },
  {
    game: "Borderlands 3",
    year: 2019,
    type: "video",
    players: 1,
    system: "Playstation 4",
  },
  {
    game: "Marvel's Spider-Man",
    year: 2018,
    type: "video",
    players: 1,
    system: "Playstation 4",
  },
  {
    game: "Quarriors!",
    year: 2011,
    type: "board",
    players: 4,
  },
  {
    game: "Hanabi",
    year: 2010,
    type: "board",
    players: 5,
  },
  {
    game: "Secret Hitler",
    year: 2016,
    type: "board",
    players: 10,
  },
  {
    game: "Tsuro",
    year: 1979,
    type: "board",
    players: 8,
  },
  {
    game: "The Settlers of Catan",
    year: 1995,
    type: "board",
    players: 4,
  },
  {
    game: "Monopoly",
    year: 1935,
    type: "board",
    players: 10,
  },
  {
    game: "Trivial Pursuit",
    year: 1979,
    type: "board",
    players: 6,
  },
  {
    game: "Shifty Eyed Spies",
    year: 2017,
    type: "board",
    players: 9,
  },
  {
    game: "Mysterium",
    year: 2015,
    type: "board",
    players: 7,
  },
];
